version: '3'
services:
  nginx:
    container_name: ${APP_NAME}_server_nginx
    build:
      context: ./src/nginx
      args:
        SERVER_NAME: ${SERVER_NAME}
        DIR_BASE: ${DIR_BASE}
        SERVER_ROOT: ${SERVER_ROOT}
        USER_ID: ${USER_ID}
    ports:
      - "80:80"
    volumes:
      - ./src/app:${DIR_BASE}
      - ./src/nginx/log:/var/log/nginx/
    links:
      - php

  php:
    container_name: ${APP_NAME}_server_php
    build:
      context: ./src/php-fpm
      args:
        USER_ID: ${USER_ID}
        DIR_BASE: ${DIR_BASE}
        HTTP_PROXY: "${HTTP_PROXY}"
        GITHUB_OAUTH: ${GITHUB_OAUTH}
    tty: true
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      PGSQL_HOST: ${PGSQL_HOST}
      PGSQL_DB_NAME: ${PGSQL_DB_NAME}
      PGSQL_USERNAME: ${PGSQL_USERNAME}
      PGSQL_PASSWORD: ${PGSQL_PASSWORD}
      PGSQL_CHARSET: ${PGSQL_CHARSET}
      PGSQL_SCHEMA: ${PGSQL_SCHEMA}

    volumes:
      - ./src/app:${DIR_BASE}
      - ./src/php-fpm/log:/var/log/php-fpm/
    ports:
      - "9000:9000"

  sass:
    build:
      context: ./src/sass
      args:
        USER_ID: ${USER_ID}
    volumes:
      - ./src/app/webroot:/app

  node:
    build:
      context: ./src/node
      args:
        USER_ID: ${USER_ID}
        DIR_BASE: ${DIR_BASE}
    volumes:
      - ./src/app:/src